  
    runtime: python39
    

    env_variables:
      HUGGINGFACEHUB_API_TOKEN: "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"
      FIREBASE_API_KEY: "AIzaSyBXdhrPNMwr-jPWG10aY8_EMpCS2ZQEN1U"
      FIREBASE_AUTH_DOMAIN: "wlf-chatbot-58449.firebaseapp.com"
      FIREBASE_PROJECT_ID: "wlf-chatbot-58449"
      FIREBASE_STORAGE_BUCKET: "wlf-chatbot-58449.firebasestorage.app"
      FIREBASE_MESSAGING_SENDER_ID: "414493982512"
      FIREBASE_APP_ID: "1:414493982512:web:a45a15b19a41f9634e52f5"
      FIREBASE_MEASUREMENT_ID: "G-4VXTX5LYKK"
      GCS_BUCKET_NAME: "wlf_chatbot_data"


    entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    

    automatic_scaling:
      min_instances: 1
      max_instances: 10
      target_cpu_utilization: 0.65
      target_throughput_utilization: 0.8