steps:

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-r', 'gs://wlf_chatbot_data', '.']


- name: 'python'
  entrypoint: 'python'
  args: ['create_llm_db.py']


- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/faiss-rag-chatbot', '.']


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/faiss-rag-chatbot']


- name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
      'run',
      'deploy',
      'faiss-rag-chatbot',
      '--image',
      'gcr.io/$PROJECT_ID/faiss-rag-chatbot',
      '--region',
      'us-central1',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      '--update-env-vars',
      'FIREBASE_API_KEY=$$FIREBASE_API_KEY,FIREBASE_AUTH_DOMAIN=$$FIREBASE_AUTH_DOMAIN,FIREBASE_PROJECT_ID=$$FIREBASE_PROJECT_ID,FIREBASE_STORAGE_BUCKET=$$FIREBASE_STORAGE_BUCKET,FIREBASE_MESSAGING_SENDER_ID=$$FIREBASE_MESSAGING_SENDER_ID,FIREBASE_APP_ID=$$FIREBASE_APP_ID,FIREBASE_MEASUREMENT_ID=$$FIREBASE_MEASUREMENT_ID,HF_TOKEN=$$HF_TOKEN'
  ]
availableSecrets:
  - secret: HF_TOKEN
    env: HF_TOKEN
  - secret: FIREBASE_API_KEY
    env: FIREBASE_API_KEY
  - secret: FIREBASE_AUTH_DOMAIN
    env: FIREBASE_AUTH_DOMAIN
  - secret: FIREBASE_PROJECT_ID
    env: FIREBASE_PROJECT_ID
  - secret: FIREBASE_STORAGE_BUCKET
    env: FIREBASE_STORAGE_BUCKET
  - secret: FIREBASE_MESSAGING_SENDER_ID
    env: FIREBASE_MESSAGING_SENDER_ID
  - secret: FIREBASE_APP_ID
    env: FIREBASE_APP_ID
  - secret: FIREBASE_MEASUREMENT_ID
    env: FIREBASE_MEASUREMENT_ID